name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'README.md'
      - 'book.toml'
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    concurrency: build-web
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          # mdbook-version: '0.4.10'
          mdbook-version: 'latest'
      - name: Build website
        run: make build
      # - name: Publish pages
      #   run: make publish
      #   env:
      #     CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
      #     CLOUDFLARE_API_TOKEN: ${{secrets.CLOUDFLARE_API_TOKEN}}

